# Commonly audited domains by proxy providers, including torrent sites and Chinese dissident media.
# Sources:
# - https://jichangtuijian.com/%E6%9C%BA%E5%9C%BA%E5%B8%B8%E8%A7%81%E5%AE%A1%E8%AE%A1%E8%A7%84%E5%88%99.html

DOMAIN-SUFFIX,nyaa.si
DOMAIN-SUFFIX,nyaa.pantsu.cat
DOMAIN-SUFFIX,rarbg.to
DOMAIN-SUFFIX,thepiratebay.org
DOMAIN-SUFFIX,1337x.to
DOMAIN-SUFFIX,yts.mx
DOMAIN-SUFFIX,eztv.re
DOMAIN-SUFFIX,torproject.org
DOMAIN-SUFFIX,minghui.org
DOMAIN-SUFFIX,minghui.net
DOMAIN-SUFFIX,epochtimes.com
DOMAIN-SUFFIX,epochtimes.fr
DOMAIN-SUFFIX,epochtimes.de
DOMAIN-SUFFIX,epochtimes.jp
DOMAIN-SUFFIX,theepochtimes.com
DOMAIN-SUFFIX,epochweekly.com
DOMAIN-SUFFIX,dajiyuan.com
DOMAIN-SUFFIX,dajiyuan.eu
DOMAIN-SUFFIX,ntdtv.com
DOMAIN-SUFFIX,ntd.tv
DOMAIN-SUFFIX,falundafa.org
DOMAIN-SUFFIX,falunaz.net
DOMAIN-SUFFIX,falungong.org
DOMAIN-SUFFIX,zhengjian.org
DOMAIN-SUFFIX,xinsheng.net
DOMAIN-SUFFIX,dafahao.com
DOMAIN-SUFFIX,dafahao.org
DOMAIN-SUFFIX,shenyun.com
DOMAIN-SUFFIX,shenyunperformingarts.org
DOMAIN-SUFFIX,tiantibooks.org
DOMAIN-SUFFIX,tuidang.org
DOMAIN-SUFFIX,9ping.com
DOMAIN-SUFFIX,ninecommentaries.com
DOMAIN-SUFFIX,dongtaiwang.com
DOMAIN-SUFFIX,wujieliulan.com
DOMAIN-SUFFIX,wujie.net
DOMAIN-SUFFIX,edoors.com
DOMAIN-SUFFIX,jinpianwang.com
DOMAIN-SUFFIX,breakgfw.com
DOMAIN-SUFFIX,aboluowang.com
DOMAIN-SUFFIX,bannedbook.org
DOMAIN-SUFFIX,secretchina.com
DOMAIN-SUFFIX,kanzhongguo.com
DOMAIN-SUFFIX,renminbao.com
DOMAIN-SUFFIX,soundofhope.org
DOMAIN-SUFFIX,boxun.com
DOMAIN-SUFFIX,creaders.net
DOMAIN-SUFFIX,chinaaid.org
DOMAIN-SUFFIX,chinadigitaltimes.net
DOMAIN-SUFFIX,64tianwang.com
DOMAIN-SUFFIX,beijingspring.com
DOMAIN-SUFFIX,chengmingmag.com
DOMAIN-SUFFIX,chenpokongvip.com
DOMAIN-SUFFIX,minzhuzhongguo.org
DOMAIN-SUFFIX,yibaochina.com
DOMAIN-SUFFIX,hrichina.org
DOMAIN-SUFFIX,weijingsheng.org
DOMAIN-SUFFIX,huaglad.com
DOMAIN-SUFFIX,oneplusnews.com
DOMAIN-SUFFIX,botanwang.com
DOMAIN-SUFFIX,zhuichaguoji.org
DOMAIN-SUFFIX,pincong.rocks
DOMAIN-SUFFIX,talk.news.pts.org.tw
DOMAIN-SUFFIX,voachinese.com
DOMAIN-SUFFIX,rfa.org
DOMAIN-SUFFIX,rfi.fr
DOMAIN-SUFFIX,dw.com
DOMAIN-SUFFIX,nytimes.com
DOMAIN-SUFFIX,mingjingnews.com
DOMAIN-SUFFIX,mingjinglive.com
DOMAIN-SUFFIX,inmediahk.net
DOMAIN-SUFFIX,xizang-zhiye.org
DOMAIN-SUFFIX,tibetpost.net
DOMAIN-SUFFIX,uhrp.org
DOMAIN-SUFFIX,uyghuramerican.org
DOMAIN-SUFFIX,dalailamaworld.com