# Internet connectivity check endpoints.

DOMAIN-SUFFIX,msftncsi.com,Direct
DOMAIN-SUFFIX,msftconnecttest.com,Direct
DOMAIN,captive.apple.com,Direct
DOMAIN,cp.cloudflare.com,Direct
DOMAIN,connectivitycheck.gstatic.com,Direct
DOMAIN,nmcheck.gnome.org,Direct
DOMAIN,networkcheck.kde.org,Direct
DOMAIN,detectportal.firefox.com,Direct
DOMAIN,network-test.debian.org,Direct
DOMAIN,ping.archlinux.org,Direct
DOMAIN,connectivity-check.ubuntu.com,Direct
DOMAIN,204.pop-os.org,Direct
URL-REGEX,^http://fedoraproject\.org/static/hotspot\.txt,Direct
URL-REGEX,^http://edge\.microsoft\.com/captiveportal/generate_204,Direct
DOMAIN,edge-http.microsoft.com,Direct
DOMAIN,connectivitycheck.gtapheneos.network,Direct
DOMAIN,grapheneos.online,Direct