# Additional reject rules. Personal use only.

DOMAIN-WILDCARD,*p2p*.chat.bilibili.com     # Bilibili live stream PCDN
DOMAIN-WILDCARD,*tracker*.chat.bilibili.com # Bilibili live stream PCDN
DOMAIN-SUFFIX,zhangyuyidong.cn              # Zhitiao