# Commonly used IP checking services. (foreign only)
# Mirrors of test-ipv6.com (Chinese excluded) are automatically included.

DOMAIN-SUFFIX,123169.xyz
DOMAIN-SUFFIX,999831.xyz
DOMAIN-SUFFIX,ip.sb
DOMAIN-SUFFIX,ip.skk.moe
DOMAIN-SUFFIX,ip.api.skk.moe
DOMAIN-SUFFIX,ipinfo.io
DOMAIN-SUFFIX,ifconfig.co
DOMAIN-SUFFIX,ifconfig.me
DOMAIN-SUFFIX,icanhazip.com
DOMAIN-SUFFIX,myip.la
DOMAIN-SUFFIX,ip-api.com
DOMAIN-SUFFIX,api.myip.la
DOMAIN-SUFFIX,ip.gs
DOMAIN-SUFFIX,ippure.com
DOMAIN-SUFFIX,ip125.com
DOMAIN-SUFFIX,ping0.cc
DOMAIN-SUFFIX,whoer.net
DOMAIN-SUFFIX,ipleak.net
DOMAIN-SUFFIX,browserleaks.com
DOMAIN-SUFFIX,dnsleaktest.com
DOMAIN-SUFFIX,checkip.amazonaws.com
DOMAIN-SUFFIX,ipify.org
DOMAIN-SUFFIX,httpbin.org
DOMAIN-SUFFIX,whatismyipaddress.com
DOMAIN-SUFFIX,ident.me
DOMAIN-SUFFIX,test-ipv6.com
DOMAIN-SUFFIX,icanhazip.com
DOMAIN-SUFFIX,ip2location.com
DOMAIN-SUFFIX,ip2location.io
DOMAIN-SUFFIX,ipapi.co